language: cpp
dist: xenial
arch:
  - amd64
  - arm64
os: linux

notifications:
  email: true
  
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libboost-dev

before_script:
  - git --version
  - cd 3rdParty/spdlog && git checkout v1.4.2 && cd ../..

script:
  - export CMAKE_BUILD_TYPE=Release CANDB__TRAVIS_BUILD=TRUE
  - ./.travis.sh
  - export CMAKE_BUILD_TYPE=Debug CANDB__TRAVIS_BUILD=TRUE
  - ./.travis.sh
    
